# name      login_host             queue      pe    mem_complex  gpu_complex
clusterA    login.clusterA.local   all.q      smp   h_vmem       gpu
clusterB    login.clusterB.local   short.q    smp   h_vmem       gpu
clusterC    login.clusterC.local   batch.q    shm   m_mem_free   ngpus
clusterD    login.clusterD.local   default.q  smp   h_vmem       gpus
